namespace Rojan.Desktop.Application.HR;

/// <summary>Write use cases for Commission rules and the Booking/Accounting-integrated commission engine.</summary>
public interface ICommissionCommandService
{
    public Task<CommissionRuleDto> CreateCommissionRuleAsync(CreateCommissionRuleRequest request, CancellationToken cancellationToken = default);

    /// <summary>
    /// The "Booking -&gt; Specialist performs service -&gt; Accounting records
    /// payment -&gt; CommissionTransaction generated" integration: scans every
    /// Accounting invoice that has been paid (in full or in part) and has a
    /// booking behind it, resolves that booking's specialist to an
    /// <see cref="EmployeeDto"/> via <see cref="EmployeeDto.SpecialistId"/>,
    /// and generates one <see cref="CommissionTransactionDto"/> per
    /// not-yet-processed invoice using that employee's
    /// <see cref="CommissionRuleDto"/> (a flat 10% default when the
    /// employee has no rule of their own). Reads Accounting/Bookings only
    /// through their own published query services - never touches their
    /// code - and is safe to call repeatedly (already-processed invoices
    /// are skipped). Returns every transaction generated by this call.
    /// </summary>
    public Task<IReadOnlyList<CommissionTransactionDto>> GenerateCommissionsFromAccountingAsync(CancellationToken cancellationToken = default);
}
