// <auto-generated>
// Hand-maintained stand-in for a Visual-Studio-generated resx Designer.cs
// (no VS resx designer tool is available in this environment) - marked
// auto-generated so analyzers treat its resx-mirrored identifiers
// (Category_Key, matching every <data name="..."> in Strings*.resx) the
// same way they treat real generated code, consistent with how a real
// ResXFileCodeGenerator output would be excluded from CA1707 etc.
// </auto-generated>
#nullable enable
using System.Globalization;
using System.Reflection;
using System.Resources;

namespace Rojan.Desktop.Presentation.Localization;

/// <summary>
/// Strongly-typed wrapper over the <c>Strings.resx</c>/<c>Strings.en.resx</c>/
/// <c>Strings.ar.resx</c> satellite resource set - hand-written rather than
/// Visual-Studio-generated (no VS resx designer tool is available in this
/// environment), but reads through the exact same
/// <see cref="System.Resources.ResourceManager"/> mechanism a generated
/// Designer.cs would use, so the standard .NET satellite-assembly
/// resolution (driven by <see cref="CultureInfo.CurrentUICulture"/>, set
/// once at startup - see <c>Shell.Localization.LocalizationService</c>)
/// applies unchanged. XAML binds these directly via
/// <c>{x:Static loc:Strings.PropertyName}</c> - safe because the selected
/// language never changes mid-session (Phase 19A's "restart required"
/// design), so there is no need for these to be reactive/bindable
/// properties.
/// </summary>
public static class Strings
{
    private static readonly ResourceManager ResourceManager =
        new("Rojan.Desktop.Presentation.Localization.Strings", typeof(Strings).GetTypeInfo().Assembly);

    private static IReadOnlyDictionary<string, string>? _packOverrides;

    /// <summary>
    /// Lets a non-built-in Language Pack supply its own string values
    /// without recompiling this assembly - the concrete proof of "Future
    /// packs load their own resources": <c>Shell.Localization.LocalizationService</c>
    /// calls this with a pack's <c>"strings"</c> table (if any) at
    /// startup. Keys the pack does not define fall through to the
    /// compiled resx (<see cref="Get"/>'s second lookup) - honest partial-
    /// translation behavior, not a hard requirement that a pack cover
    /// every key.
    /// </summary>
    public static void SetPackOverrides(IReadOnlyDictionary<string, string>? overrides) => _packOverrides = overrides;

    private static string Get(string key)
    {
        if (_packOverrides is not null && _packOverrides.TryGetValue(key, out var overrideValue))
        {
            return overrideValue;
        }

        return ResourceManager.GetString(key, CultureInfo.CurrentUICulture) ?? key;
    }

    public static string Common_Search => Get(nameof(Common_Search));

    public static string Common_Back => Get(nameof(Common_Back));

    public static string Common_Forward => Get(nameof(Common_Forward));

    public static string Common_Notifications => Get(nameof(Common_Notifications));

    public static string Common_GuestUser => Get(nameof(Common_GuestUser));

    public static string Common_Minimize => Get(nameof(Common_Minimize));

    public static string Common_Maximize => Get(nameof(Common_Maximize));

    public static string Common_Close => Get(nameof(Common_Close));

    public static string Common_CollapseExpandNavigation => Get(nameof(Common_CollapseExpandNavigation));

    public static string Common_NoNotifications => Get(nameof(Common_NoNotifications));

    public static string Common_Loading => Get(nameof(Common_Loading));

    public static string Common_NoDataAvailable => Get(nameof(Common_NoDataAvailable));

    public static string Common_Retry => Get(nameof(Common_Retry));

    public static string Common_Ready => Get(nameof(Common_Ready));

    public static string Common_Home => Get(nameof(Common_Home));

    public static string Common_ViewingFormat => Get(nameof(Common_ViewingFormat));

    public static string Common_ErrorDialogMessage => Get(nameof(Common_ErrorDialogMessage));

    public static string Common_Save => Get(nameof(Common_Save));

    public static string Common_Cancel => Get(nameof(Common_Cancel));

    public static string Dashboard_Title => Get(nameof(Dashboard_Title));

    public static string Dashboard_Subtitle => Get(nameof(Dashboard_Subtitle));

    public static string Dashboard_KeyMetrics => Get(nameof(Dashboard_KeyMetrics));

    public static string Dashboard_QuickActions => Get(nameof(Dashboard_QuickActions));

    public static string Dashboard_RecentActivity => Get(nameof(Dashboard_RecentActivity));

    public static string Dashboard_AiAssistant => Get(nameof(Dashboard_AiAssistant));

    public static string Dashboard_ComingSoon => Get(nameof(Dashboard_ComingSoon));

    public static string Dashboard_AskAi => Get(nameof(Dashboard_AskAi));

    public static string Dashboard_QuickAction_NewBooking => Get(nameof(Dashboard_QuickAction_NewBooking));

    public static string Dashboard_QuickAction_AddClient => Get(nameof(Dashboard_QuickAction_AddClient));

    public static string Dashboard_QuickAction_CreateTask => Get(nameof(Dashboard_QuickAction_CreateTask));

    public static string Dashboard_QuickAction_ViewReports => Get(nameof(Dashboard_QuickAction_ViewReports));

    public static string Dashboard_Kpi_TotalBookings => Get(nameof(Dashboard_Kpi_TotalBookings));

    public static string Dashboard_Kpi_ActiveClients => Get(nameof(Dashboard_Kpi_ActiveClients));

    public static string Dashboard_Kpi_RevenueMtd => Get(nameof(Dashboard_Kpi_RevenueMtd));

    public static string Dashboard_Kpi_PendingTasks => Get(nameof(Dashboard_Kpi_PendingTasks));

    public static string Dashboard_Activity_NewBooking => Get(nameof(Dashboard_Activity_NewBooking));

    public static string Dashboard_Activity_ProfileUpdated => Get(nameof(Dashboard_Activity_ProfileUpdated));

    public static string Dashboard_Activity_PaymentReceived => Get(nameof(Dashboard_Activity_PaymentReceived));

    public static string Dashboard_Activity_TaskCompleted => Get(nameof(Dashboard_Activity_TaskCompleted));

    public static string Nav_Dashboard => Get(nameof(Nav_Dashboard));

    public static string Nav_Customers => Get(nameof(Nav_Customers));

    public static string Nav_Bookings => Get(nameof(Nav_Bookings));

    public static string Nav_Calendar => Get(nameof(Nav_Calendar));

    public static string Nav_Services => Get(nameof(Nav_Services));

    public static string Nav_Inventory => Get(nameof(Nav_Inventory));

    public static string Nav_Accounting => Get(nameof(Nav_Accounting));

    public static string Nav_StaffHr => Get(nameof(Nav_StaffHr));

    public static string Nav_Specialists => Get(nameof(Nav_Specialists));

    public static string Nav_Reports => Get(nameof(Nav_Reports));

    public static string Nav_Analytics => Get(nameof(Nav_Analytics));

    public static string Nav_AiCenter => Get(nameof(Nav_AiCenter));

    public static string Nav_Settings => Get(nameof(Nav_Settings));

    public static string Settings_Title => Get(nameof(Settings_Title));

    public static string Settings_Subtitle => Get(nameof(Settings_Subtitle));

    public static string Settings_Language_SectionTitle => Get(nameof(Settings_Language_SectionTitle));

    public static string Settings_Language_BuiltIn => Get(nameof(Settings_Language_BuiltIn));

    public static string Settings_Language_InstalledPacks => Get(nameof(Settings_Language_InstalledPacks));

    public static string Settings_Language_AvailableLanguages => Get(nameof(Settings_Language_AvailableLanguages));

    public static string Settings_Language_Download => Get(nameof(Settings_Language_Download));

    public static string Settings_Language_Install => Get(nameof(Settings_Language_Install));

    public static string Settings_Language_Remove => Get(nameof(Settings_Language_Remove));

    public static string Settings_Language_Update => Get(nameof(Settings_Language_Update));

    public static string Settings_Language_ComingSoon => Get(nameof(Settings_Language_ComingSoon));

    public static string Settings_Language_Apply => Get(nameof(Settings_Language_Apply));

    public static string Settings_Language_RestartRequired => Get(nameof(Settings_Language_RestartRequired));

    public static string Settings_Language_RestartNow => Get(nameof(Settings_Language_RestartNow));

    public static string Settings_Language_CurrentFormat => Get(nameof(Settings_Language_CurrentFormat));

    public static string Settings_Language_NoPacksInstalled => Get(nameof(Settings_Language_NoPacksInstalled));

    public static string Settings_Theme_SectionTitle => Get(nameof(Settings_Theme_SectionTitle));

    public static string Settings_Theme_Light => Get(nameof(Settings_Theme_Light));

    public static string Settings_Theme_Dark => Get(nameof(Settings_Theme_Dark));

    public static string Settings_Theme_System => Get(nameof(Settings_Theme_System));

    public static string Settings_Theme_CurrentFormat => Get(nameof(Settings_Theme_CurrentFormat));

    public static string Settings_Theme_Apply => Get(nameof(Settings_Theme_Apply));

    public static string Settings_Theme_RestartRequired => Get(nameof(Settings_Theme_RestartRequired));

    public static string Settings_Theme_RestartNow => Get(nameof(Settings_Theme_RestartNow));

    public static string Nav_Organizations => Get(nameof(Nav_Organizations));

    public static string Shell_BranchSwitcher => Get(nameof(Shell_BranchSwitcher));

    public static string Organizations_Title => Get(nameof(Organizations_Title));

    public static string Organizations_Subtitle => Get(nameof(Organizations_Subtitle));

    public static string Organizations_Refresh => Get(nameof(Organizations_Refresh));

    public static string Organizations_Section_Organizations => Get(nameof(Organizations_Section_Organizations));

    public static string Organizations_Section_Branches => Get(nameof(Organizations_Section_Branches));

    public static string Organizations_Section_BranchSettings => Get(nameof(Organizations_Section_BranchSettings));

    public static string Organizations_Section_Permissions => Get(nameof(Organizations_Section_Permissions));

    public static string Organizations_Section_Session => Get(nameof(Organizations_Section_Session));

    public static string Organizations_CreateOrganization => Get(nameof(Organizations_CreateOrganization));

    public static string Organizations_Name => Get(nameof(Organizations_Name));

    public static string Organizations_LegalName => Get(nameof(Organizations_LegalName));

    public static string Organizations_TaxInformation => Get(nameof(Organizations_TaxInformation));

    public static string Organizations_Subscription => Get(nameof(Organizations_Subscription));

    public static string Organizations_AllOrganizations => Get(nameof(Organizations_AllOrganizations));

    public static string Organizations_CreateBranch => Get(nameof(Organizations_CreateBranch));

    public static string Organizations_BranchName => Get(nameof(Organizations_BranchName));

    public static string Organizations_BranchCode => Get(nameof(Organizations_BranchCode));

    public static string Organizations_BranchAddress => Get(nameof(Organizations_BranchAddress));

    public static string Organizations_BranchPhone => Get(nameof(Organizations_BranchPhone));

    public static string Organizations_BranchEmail => Get(nameof(Organizations_BranchEmail));

    public static string Organizations_BranchManager => Get(nameof(Organizations_BranchManager));

    public static string Organizations_BranchTimeZone => Get(nameof(Organizations_BranchTimeZone));

    public static string Organizations_BranchCurrency => Get(nameof(Organizations_BranchCurrency));

    public static string Organizations_AllBranches => Get(nameof(Organizations_AllBranches));

    public static string Organizations_OpenTime => Get(nameof(Organizations_OpenTime));

    public static string Organizations_CloseTime => Get(nameof(Organizations_CloseTime));

    public static string Organizations_WorkingDays => Get(nameof(Organizations_WorkingDays));

    public static string Organizations_Monday => Get(nameof(Organizations_Monday));

    public static string Organizations_Tuesday => Get(nameof(Organizations_Tuesday));

    public static string Organizations_Wednesday => Get(nameof(Organizations_Wednesday));

    public static string Organizations_Thursday => Get(nameof(Organizations_Thursday));

    public static string Organizations_Friday => Get(nameof(Organizations_Friday));

    public static string Organizations_Saturday => Get(nameof(Organizations_Saturday));

    public static string Organizations_Sunday => Get(nameof(Organizations_Sunday));

    public static string Organizations_VatPercentage => Get(nameof(Organizations_VatPercentage));

    public static string Organizations_ReceiptHeader => Get(nameof(Organizations_ReceiptHeader));

    public static string Organizations_ReceiptFooter => Get(nameof(Organizations_ReceiptFooter));

    public static string Organizations_ShowLogo => Get(nameof(Organizations_ShowLogo));

    public static string Organizations_MinNoticeHours => Get(nameof(Organizations_MinNoticeHours));

    public static string Organizations_MaxAdvanceBookingDays => Get(nameof(Organizations_MaxAdvanceBookingDays));

    public static string Organizations_AllowSameDayBooking => Get(nameof(Organizations_AllowSameDayBooking));

    public static string Organizations_EmailEnabled => Get(nameof(Organizations_EmailEnabled));

    public static string Organizations_SmsEnabled => Get(nameof(Organizations_SmsEnabled));

    public static string Organizations_ReminderHours => Get(nameof(Organizations_ReminderHours));

    public static string Organizations_SaveSettings => Get(nameof(Organizations_SaveSettings));

    public static string Organizations_SettingsSaved => Get(nameof(Organizations_SettingsSaved));

    public static string Organizations_CurrentOrganization => Get(nameof(Organizations_CurrentOrganization));

    public static string Organizations_CurrentBranch => Get(nameof(Organizations_CurrentBranch));

    public static string Organizations_CurrentRole => Get(nameof(Organizations_CurrentRole));

    public static string Organizations_SwitchRole => Get(nameof(Organizations_SwitchRole));

    public static string Organizations_Code => Get(nameof(Organizations_Code));

    public static string Organizations_OrgPhone => Get(nameof(Organizations_OrgPhone));

    public static string Organizations_OrgEmail => Get(nameof(Organizations_OrgEmail));

    public static string Organizations_OrgAddress => Get(nameof(Organizations_OrgAddress));

    public static string Shell_BranchSwitcher_SearchPlaceholder => Get(nameof(Shell_BranchSwitcher_SearchPlaceholder));

    public static string Shell_BranchSwitcher_Favorites => Get(nameof(Shell_BranchSwitcher_Favorites));

    public static string Shell_BranchSwitcher_Recent => Get(nameof(Shell_BranchSwitcher_Recent));

    // Enterprise UX/UI Refinement pass - shared field-label/action keys reused across multiple modules.
    public static string Common_Export => Get(nameof(Common_Export));

    public static string Common_SaveChanges => Get(nameof(Common_SaveChanges));

    public static string Common_Daily => Get(nameof(Common_Daily));

    public static string Common_Weekly => Get(nameof(Common_Weekly));

    public static string Common_Monthly => Get(nameof(Common_Monthly));

    public static string Common_FullName => Get(nameof(Common_FullName));

    public static string Common_Email => Get(nameof(Common_Email));

    public static string Common_Phone => Get(nameof(Common_Phone));

    public static string Common_Notes => Get(nameof(Common_Notes));

    public static string Common_Description => Get(nameof(Common_Description));

    public static string Common_Date => Get(nameof(Common_Date));

    public static string Common_Type => Get(nameof(Common_Type));

    public static string Common_Quantity => Get(nameof(Common_Quantity));

    public static string Common_Name => Get(nameof(Common_Name));

    public static string Common_Category => Get(nameof(Common_Category));

    public static string Common_Specialist => Get(nameof(Common_Specialist));

    public static string Common_Service => Get(nameof(Common_Service));

    public static string Common_Customer => Get(nameof(Common_Customer));

    public static string Common_Status => Get(nameof(Common_Status));

    public static string Common_Duration => Get(nameof(Common_Duration));

    public static string Common_MinutesShort => Get(nameof(Common_MinutesShort));

    public static string Common_Confirm => Get(nameof(Common_Confirm));

    public static string Common_Next => Get(nameof(Common_Next));

    public static string Common_Done => Get(nameof(Common_Done));

    public static string Common_Add => Get(nameof(Common_Add));

    public static string Common_Send => Get(nameof(Common_Send));

    public static string Common_Delete => Get(nameof(Common_Delete));

    public static string Common_Enabled => Get(nameof(Common_Enabled));

    public static string Common_Supplier => Get(nameof(Common_Supplier));

    public static string Common_Price => Get(nameof(Common_Price));

    public static string Modules_NotImplementedYet => Get(nameof(Modules_NotImplementedYet));

    public static string ExportDialog_Title => Get(nameof(ExportDialog_Title));

    public static string ExportDialog_Format => Get(nameof(ExportDialog_Format));

    public static string Calendar_Title => Get(nameof(Calendar_Title));

    public static string Calendar_Subtitle => Get(nameof(Calendar_Subtitle));

    public static string Calendar_SpecialistAndDate => Get(nameof(Calendar_SpecialistAndDate));

    public static string Calendar_Availability => Get(nameof(Calendar_Availability));

    public static string Analytics_Title => Get(nameof(Analytics_Title));

    public static string Analytics_Subtitle => Get(nameof(Analytics_Subtitle));

    public static string Analytics_KpiCards => Get(nameof(Analytics_KpiCards));

    public static string BookingWizard_Title => Get(nameof(BookingWizard_Title));

    public static string BookingWizard_Confirmed => Get(nameof(BookingWizard_Confirmed));

    public static string BookingWizard_StepWhoFor => Get(nameof(BookingWizard_StepWhoFor));

    public static string BookingWizard_StepChooseService => Get(nameof(BookingWizard_StepChooseService));

    public static string BookingWizard_StepChooseSpecialist => Get(nameof(BookingWizard_StepChooseSpecialist));

    public static string BookingWizard_StepChooseDate => Get(nameof(BookingWizard_StepChooseDate));

    public static string BookingWizard_StepChooseTime => Get(nameof(BookingWizard_StepChooseTime));

    public static string BookingWizard_StepReview => Get(nameof(BookingWizard_StepReview));

    public static string BookingWizard_NoSlots => Get(nameof(BookingWizard_NoSlots));

    public static string BookingWizard_ConfirmBooking => Get(nameof(BookingWizard_ConfirmBooking));

    public static string Specialists_Title => Get(nameof(Specialists_Title));

    public static string Specialists_Subtitle => Get(nameof(Specialists_Subtitle));

    public static string Specialists_AddSpecialist => Get(nameof(Specialists_AddSpecialist));

    public static string Specialists_JobTitle => Get(nameof(Specialists_JobTitle));

    public static string Specialists_SearchPlaceholder => Get(nameof(Specialists_SearchPlaceholder));

    public static string Specialists_AllSpecialists => Get(nameof(Specialists_AllSpecialists));

    public static string Specialists_SelectPrompt => Get(nameof(Specialists_SelectPrompt));

    public static string Specialists_Skills => Get(nameof(Specialists_Skills));

    public static string Specialists_AddSkill => Get(nameof(Specialists_AddSkill));

    public static string Services_Title => Get(nameof(Services_Title));

    public static string Services_Subtitle => Get(nameof(Services_Subtitle));

    public static string Services_SearchPlaceholder => Get(nameof(Services_SearchPlaceholder));

    public static string Services_AllServices => Get(nameof(Services_AllServices));

    public static string Services_Details => Get(nameof(Services_Details));

    public static string Services_AssignedSpecialists => Get(nameof(Services_AssignedSpecialists));

    public static string Services_SelectPrompt => Get(nameof(Services_SelectPrompt));

    public static string Services_Assign => Get(nameof(Services_Assign));

    public static string Bookings_Title => Get(nameof(Bookings_Title));

    public static string Bookings_Subtitle => Get(nameof(Bookings_Subtitle));

    public static string Bookings_NewBookingWizard => Get(nameof(Bookings_NewBookingWizard));

    public static string Bookings_NewBooking => Get(nameof(Bookings_NewBooking));

    public static string Bookings_DurationMin => Get(nameof(Bookings_DurationMin));

    public static string Bookings_AddBooking => Get(nameof(Bookings_AddBooking));

    public static string Bookings_AllBookings => Get(nameof(Bookings_AllBookings));

    public static string Bookings_When => Get(nameof(Bookings_When));

    public static string Bookings_SelectPrompt => Get(nameof(Bookings_SelectPrompt));

    public static string Bookings_Complete => Get(nameof(Bookings_Complete));

    public static string Bookings_Details => Get(nameof(Bookings_Details));

    public static string Customers_Title => Get(nameof(Customers_Title));

    public static string Customers_Subtitle => Get(nameof(Customers_Subtitle));

    public static string Customers_AddCustomer => Get(nameof(Customers_AddCustomer));

    public static string Customers_Company => Get(nameof(Customers_Company));

    public static string Customers_SearchPlaceholder => Get(nameof(Customers_SearchPlaceholder));

    public static string Customers_AllCustomers => Get(nameof(Customers_AllCustomers));

    public static string Customers_SelectPrompt => Get(nameof(Customers_SelectPrompt));

    public static string Customers_Statistics => Get(nameof(Customers_Statistics));

    public static string Customers_Tags => Get(nameof(Customers_Tags));

    public static string Customers_Timeline => Get(nameof(Customers_Timeline));

    public static string Customers_AddTag => Get(nameof(Customers_AddTag));

    public static string Customers_AddNote => Get(nameof(Customers_AddNote));

    public static string Inventory_Title => Get(nameof(Inventory_Title));

    public static string Inventory_Subtitle => Get(nameof(Inventory_Subtitle));

    public static string Inventory_CategoriesSuppliers => Get(nameof(Inventory_CategoriesSuppliers));

    public static string Inventory_NewProduct => Get(nameof(Inventory_NewProduct));

    public static string Inventory_Stock => Get(nameof(Inventory_Stock));

    public static string Inventory_RecentTransactions => Get(nameof(Inventory_RecentTransactions));

    public static string Inventory_LinkedServices => Get(nameof(Inventory_LinkedServices));

    public static string Inventory_AllProducts => Get(nameof(Inventory_AllProducts));

    public static string Inventory_AddCategory => Get(nameof(Inventory_AddCategory));

    public static string Inventory_AddSupplier => Get(nameof(Inventory_AddSupplier));

    public static string Inventory_AddProduct => Get(nameof(Inventory_AddProduct));

    public static string Inventory_RecordTransaction => Get(nameof(Inventory_RecordTransaction));

    public static string Inventory_Map => Get(nameof(Inventory_Map));

    public static string Inventory_Sku => Get(nameof(Inventory_Sku));

    public static string Inventory_UnitPrice => Get(nameof(Inventory_UnitPrice));

    public static string Inventory_InitialQuantity => Get(nameof(Inventory_InitialQuantity));

    public static string Inventory_ReorderThreshold => Get(nameof(Inventory_ReorderThreshold));

    public static string Inventory_SearchPlaceholder => Get(nameof(Inventory_SearchPlaceholder));

    public static string Inventory_SelectPrompt => Get(nameof(Inventory_SelectPrompt));

    public static string Inventory_LowStockWarning => Get(nameof(Inventory_LowStockWarning));

    public static string Inventory_TotalProducts => Get(nameof(Inventory_TotalProducts));

    public static string Inventory_LowStockItems => Get(nameof(Inventory_LowStockItems));

    public static string Inventory_OnHand => Get(nameof(Inventory_OnHand));

    public static string Inventory_ReorderAt => Get(nameof(Inventory_ReorderAt));

    public static string Accounting_Title => Get(nameof(Accounting_Title));

    public static string Accounting_Subtitle => Get(nameof(Accounting_Subtitle));

    public static string Accounting_NewSalePos => Get(nameof(Accounting_NewSalePos));

    public static string Accounting_CancelInvoice => Get(nameof(Accounting_CancelInvoice));

    public static string Accounting_SearchPlaceholder => Get(nameof(Accounting_SearchPlaceholder));

    public static string Accounting_AllInvoices => Get(nameof(Accounting_AllInvoices));

    public static string Accounting_LineItems => Get(nameof(Accounting_LineItems));

    public static string Accounting_Payments => Get(nameof(Accounting_Payments));

    public static string Accounting_Receipts => Get(nameof(Accounting_Receipts));

    public static string Accounting_SelectPrompt => Get(nameof(Accounting_SelectPrompt));

    public static string Accounting_Subtotal => Get(nameof(Accounting_Subtotal));

    public static string Accounting_Tax => Get(nameof(Accounting_Tax));

    public static string Accounting_Total => Get(nameof(Accounting_Total));

    public static string Accounting_TotalRevenue => Get(nameof(Accounting_TotalRevenue));

    public static string Accounting_Today => Get(nameof(Accounting_Today));

    public static string Accounting_Outstanding => Get(nameof(Accounting_Outstanding));

    public static string Accounting_PaidInvoices => Get(nameof(Accounting_PaidInvoices));

    public static string Pos_NewSale => Get(nameof(Pos_NewSale));

    public static string Pos_PaymentRecorded => Get(nameof(Pos_PaymentRecorded));

    public static string Pos_BookingOptional => Get(nameof(Pos_BookingOptional));

    public static string Pos_PaymentMethod => Get(nameof(Pos_PaymentMethod));

    public static string Pos_AmountTendered => Get(nameof(Pos_AmountTendered));

    public static string Pos_AddProduct => Get(nameof(Pos_AddProduct));

    public static string Pos_AddService => Get(nameof(Pos_AddService));

    public static string Pos_Cart => Get(nameof(Pos_Cart));

    public static string Pos_ProceedToPayment => Get(nameof(Pos_ProceedToPayment));

    public static string Pos_Charge => Get(nameof(Pos_Charge));

    public static string Pos_AmountDue => Get(nameof(Pos_AmountDue));

    public static string Pos_ChangeDue => Get(nameof(Pos_ChangeDue));

    public static string Pos_Paid => Get(nameof(Pos_Paid));

    public static string Pos_Via => Get(nameof(Pos_Via));

    public static string Pos_InvoiceTotal => Get(nameof(Pos_InvoiceTotal));

    public static string Reporting_Title => Get(nameof(Reporting_Title));

    public static string Reporting_Subtitle => Get(nameof(Reporting_Subtitle));

    public static string Reporting_Catalog => Get(nameof(Reporting_Catalog));

    public static string Reporting_ReportViewer => Get(nameof(Reporting_ReportViewer));

    public static string Reporting_SavedReports => Get(nameof(Reporting_SavedReports));

    public static string Reporting_RecentReports => Get(nameof(Reporting_RecentReports));

    public static string Reporting_ReportCatalog => Get(nameof(Reporting_ReportCatalog));

    public static string Reporting_FilterPanel => Get(nameof(Reporting_FilterPanel));

    public static string Reporting_Results => Get(nameof(Reporting_Results));

    public static string Reporting_DateRangeStart => Get(nameof(Reporting_DateRangeStart));

    public static string Reporting_DateRangeEnd => Get(nameof(Reporting_DateRangeEnd));

    public static string Reporting_RunPrompt => Get(nameof(Reporting_RunPrompt));

    public static string Reporting_AddFilter => Get(nameof(Reporting_AddFilter));

    public static string Reporting_RunReport => Get(nameof(Reporting_RunReport));

    public static string Reporting_Rerun => Get(nameof(Reporting_Rerun));

    public static string Reporting_Unpin => Get(nameof(Reporting_Unpin));

    public static string Reporting_Pin => Get(nameof(Reporting_Pin));

    public static string Reporting_Report => Get(nameof(Reporting_Report));

    public static string Reporting_NoneSelected => Get(nameof(Reporting_NoneSelected));

    public static string Reporting_Rows => Get(nameof(Reporting_Rows));

    public static string Ai_Title => Get(nameof(Ai_Title));

    public static string Ai_Subtitle => Get(nameof(Ai_Subtitle));

    public static string Ai_Section_Home => Get(nameof(Ai_Section_Home));

    public static string Ai_Section_Chat => Get(nameof(Ai_Section_Chat));

    public static string Ai_Section_Insights => Get(nameof(Ai_Section_Insights));

    public static string Ai_Section_Recommendations => Get(nameof(Ai_Section_Recommendations));

    public static string Ai_Section_History => Get(nameof(Ai_Section_History));

    public static string Ai_Section_Settings => Get(nameof(Ai_Section_Settings));

    public static string Ai_BusinessHealthScore => Get(nameof(Ai_BusinessHealthScore));

    public static string Ai_DailySummary => Get(nameof(Ai_DailySummary));

    public static string Ai_SmartNotifications => Get(nameof(Ai_SmartNotifications));

    public static string Ai_BusinessAssistant => Get(nameof(Ai_BusinessAssistant));

    public static string Ai_NewConversation => Get(nameof(Ai_NewConversation));

    public static string Ai_InsightDashboard => Get(nameof(Ai_InsightDashboard));

    public static string Ai_RecommendationsPanel => Get(nameof(Ai_RecommendationsPanel));

    public static string Ai_ActionCenterSuggestedTasks => Get(nameof(Ai_ActionCenterSuggestedTasks));

    public static string Ai_SearchConversations => Get(nameof(Ai_SearchConversations));

    public static string Ai_ClearHistory => Get(nameof(Ai_ClearHistory));

    public static string Ai_PinnedConversations => Get(nameof(Ai_PinnedConversations));

    public static string Ai_RecentConversations => Get(nameof(Ai_RecentConversations));

    public static string Ai_ExportPreview => Get(nameof(Ai_ExportPreview));

    public static string Ai_FeatureToggles => Get(nameof(Ai_FeatureToggles));

    public static string Ai_AutoGenerateRecommendations => Get(nameof(Ai_AutoGenerateRecommendations));

    public static string Ai_SaveSettings => Get(nameof(Ai_SaveSettings));

    public static string Ai_ModelSelector => Get(nameof(Ai_ModelSelector));

    public static string Ai_Provider => Get(nameof(Ai_Provider));

    public static string Ai_ModelId => Get(nameof(Ai_ModelId));

    public static string Ai_SaveModelConfiguration => Get(nameof(Ai_SaveModelConfiguration));

    public static string Ai_UsageDashboard => Get(nameof(Ai_UsageDashboard));

    public static string Ai_TotalTokensUsed => Get(nameof(Ai_TotalTokensUsed));

    public static string Ai_Tokens => Get(nameof(Ai_Tokens));

    public static string Ai_PromptTemplates => Get(nameof(Ai_PromptTemplates));

    public static string Hr_Title => Get(nameof(Hr_Title));

    public static string Hr_Subtitle => Get(nameof(Hr_Subtitle));

    public static string Hr_Employees => Get(nameof(Hr_Employees));

    public static string Hr_PresentToday => Get(nameof(Hr_PresentToday));

    public static string Hr_LateToday => Get(nameof(Hr_LateToday));

    public static string Hr_OnLeave => Get(nameof(Hr_OnLeave));

    public static string Hr_PayrollThisMonth => Get(nameof(Hr_PayrollThisMonth));

    public static string Hr_CommissionThisMonth => Get(nameof(Hr_CommissionThisMonth));

    public static string Hr_AvgAttendance => Get(nameof(Hr_AvgAttendance));

    public static string Hr_Attendance => Get(nameof(Hr_Attendance));

    public static string Hr_Shifts => Get(nameof(Hr_Shifts));

    public static string Hr_Leave => Get(nameof(Hr_Leave));

    public static string Hr_Commission => Get(nameof(Hr_Commission));

    public static string Hr_Payroll => Get(nameof(Hr_Payroll));

    public static string Hr_AddEmployee => Get(nameof(Hr_AddEmployee));

    public static string Hr_BaseSalary => Get(nameof(Hr_BaseSalary));

    public static string Hr_Role => Get(nameof(Hr_Role));

    public static string Hr_Department => Get(nameof(Hr_Department));

    public static string Hr_EmploymentType => Get(nameof(Hr_EmploymentType));

    public static string Hr_SearchPlaceholder => Get(nameof(Hr_SearchPlaceholder));

    public static string Hr_AllEmployees => Get(nameof(Hr_AllEmployees));

    public static string Hr_RecordAttendanceToday => Get(nameof(Hr_RecordAttendanceToday));

    public static string Hr_Employee => Get(nameof(Hr_Employee));

    public static string Hr_CheckInTime => Get(nameof(Hr_CheckInTime));

    public static string Hr_RecordAttendance => Get(nameof(Hr_RecordAttendance));

    public static string Hr_TodayAttendance => Get(nameof(Hr_TodayAttendance));

    public static string Hr_CreateShift => Get(nameof(Hr_CreateShift));

    public static string Hr_Label => Get(nameof(Hr_Label));

    public static string Hr_StartTime => Get(nameof(Hr_StartTime));

    public static string Hr_EndTime => Get(nameof(Hr_EndTime));

    public static string Hr_AssignShift => Get(nameof(Hr_AssignShift));

    public static string Hr_Shift => Get(nameof(Hr_Shift));

    public static string Hr_ShiftAssignments => Get(nameof(Hr_ShiftAssignments));

    public static string Hr_RequestLeave => Get(nameof(Hr_RequestLeave));

    public static string Hr_StartDate => Get(nameof(Hr_StartDate));

    public static string Hr_EndDate => Get(nameof(Hr_EndDate));

    public static string Hr_Reason => Get(nameof(Hr_Reason));

    public static string Hr_LeaveRequests => Get(nameof(Hr_LeaveRequests));

    public static string Hr_Approve => Get(nameof(Hr_Approve));

    public static string Hr_Reject => Get(nameof(Hr_Reject));

    public static string Hr_CommissionEngine => Get(nameof(Hr_CommissionEngine));

    public static string Hr_CommissionEngineDescription => Get(nameof(Hr_CommissionEngineDescription));

    public static string Hr_GenerateCommissions => Get(nameof(Hr_GenerateCommissions));

    public static string Hr_AddCommissionRule => Get(nameof(Hr_AddCommissionRule));

    public static string Hr_AddRule => Get(nameof(Hr_AddRule));

    public static string Hr_CommissionValueHint => Get(nameof(Hr_CommissionValueHint));

    public static string Hr_CommissionRules => Get(nameof(Hr_CommissionRules));

    public static string Hr_CommissionHistory => Get(nameof(Hr_CommissionHistory));

    public static string Hr_Invoice => Get(nameof(Hr_Invoice));

    public static string Hr_GeneratePayrollSummary => Get(nameof(Hr_GeneratePayrollSummary));

    public static string Hr_Month => Get(nameof(Hr_Month));

    public static string Hr_Year => Get(nameof(Hr_Year));

    public static string Hr_Bonus => Get(nameof(Hr_Bonus));

    public static string Hr_Deduction => Get(nameof(Hr_Deduction));

    public static string Hr_GeneratePayroll => Get(nameof(Hr_GeneratePayroll));

    public static string Hr_PayrollSummaries => Get(nameof(Hr_PayrollSummaries));

    public static string Hr_Base => Get(nameof(Hr_Base));

    public static string Hr_SelectPrompt => Get(nameof(Hr_SelectPrompt));

    public static string Hr_Activate => Get(nameof(Hr_Activate));

    public static string Hr_Deactivate => Get(nameof(Hr_Deactivate));

    public static string Hr_Suspend => Get(nameof(Hr_Suspend));

    public static string Hr_RecentAttendance => Get(nameof(Hr_RecentAttendance));

    public static string Hr_UpcomingShifts => Get(nameof(Hr_UpcomingShifts));

    public static string Hr_RecentCommissions => Get(nameof(Hr_RecentCommissions));

    public static string Help_Button_Tooltip => Get(nameof(Help_Button_Tooltip));

    public static string Help_Search_Placeholder => Get(nameof(Help_Search_Placeholder));

    public static string Help_Search_NoResults => Get(nameof(Help_Search_NoResults));

    public static string Help_Search_RecentSearches => Get(nameof(Help_Search_RecentSearches));

    public static string Help_Section_Purpose => Get(nameof(Help_Section_Purpose));

    public static string Help_Section_Overview => Get(nameof(Help_Section_Overview));

    public static string Help_Section_WhenToUse => Get(nameof(Help_Section_WhenToUse));

    public static string Help_Section_Steps => Get(nameof(Help_Section_Steps));

    public static string Help_Section_Tips => Get(nameof(Help_Section_Tips));

    public static string Help_Section_Warnings => Get(nameof(Help_Section_Warnings));

    public static string Help_Section_BestPractices => Get(nameof(Help_Section_BestPractices));

    public static string Help_Section_Notes => Get(nameof(Help_Section_Notes));

    public static string Help_Section_Shortcuts => Get(nameof(Help_Section_Shortcuts));

    public static string Help_Section_RelatedTopics => Get(nameof(Help_Section_RelatedTopics));

    public static string Help_Section_AiSuggestions => Get(nameof(Help_Section_AiSuggestions));

    public static string Help_AiSuggestions_ComingSoon => Get(nameof(Help_AiSuggestions_ComingSoon));

    public static string Help_Nav_Back => Get(nameof(Help_Nav_Back));

    public static string Help_Nav_Forward => Get(nameof(Help_Nav_Forward));

    public static string Help_Nav_RecentlyViewed => Get(nameof(Help_Nav_RecentlyViewed));

    public static string Help_Nav_AddFavorite => Get(nameof(Help_Nav_AddFavorite));

    public static string Help_Nav_RemoveFavorite => Get(nameof(Help_Nav_RemoveFavorite));

    public static string Help_Breadcrumb_Home => Get(nameof(Help_Breadcrumb_Home));

    // Phase 27: Enterprise Notification Center.
    public static string Notification_Search_Placeholder => Get(nameof(Notification_Search_Placeholder));

    public static string Notification_Filter_All => Get(nameof(Notification_Filter_All));

    public static string Notification_Filter_Unread => Get(nameof(Notification_Filter_Unread));

    public static string Notification_MarkAllRead => Get(nameof(Notification_MarkAllRead));

    public static string Notification_ClearAll => Get(nameof(Notification_ClearAll));

    public static string Notification_Dismiss => Get(nameof(Notification_Dismiss));

    public static string Notification_NoResults => Get(nameof(Notification_NoResults));

    public static string Notification_SilentMode => Get(nameof(Notification_SilentMode));

    public static string Notification_SilentMode_Description => Get(nameof(Notification_SilentMode_Description));

    public static string Notification_Toast_Close => Get(nameof(Notification_Toast_Close));

    public static string Notification_Category_System => Get(nameof(Notification_Category_System));

    public static string Notification_Category_Customers => Get(nameof(Notification_Category_Customers));

    public static string Notification_Category_Bookings => Get(nameof(Notification_Category_Bookings));

    public static string Notification_Category_Inventory => Get(nameof(Notification_Category_Inventory));

    public static string Notification_Category_Sync => Get(nameof(Notification_Category_Sync));

    public static string Notification_Demo_WelcomeTitle => Get(nameof(Notification_Demo_WelcomeTitle));

    public static string Notification_Demo_WelcomeMessage => Get(nameof(Notification_Demo_WelcomeMessage));

    public static string Notification_Demo_BackupSuccessTitle => Get(nameof(Notification_Demo_BackupSuccessTitle));

    public static string Notification_Demo_BackupSuccessMessage => Get(nameof(Notification_Demo_BackupSuccessMessage));

    public static string Notification_Demo_LowStockTitle => Get(nameof(Notification_Demo_LowStockTitle));

    public static string Notification_Demo_LowStockMessage => Get(nameof(Notification_Demo_LowStockMessage));

    public static string Notification_Demo_SyncFailedTitle => Get(nameof(Notification_Demo_SyncFailedTitle));

    public static string Notification_Demo_SyncFailedMessage => Get(nameof(Notification_Demo_SyncFailedMessage));

    public static string Notification_Demo_NewBookingTitle => Get(nameof(Notification_Demo_NewBookingTitle));

    public static string Notification_Demo_NewBookingMessage => Get(nameof(Notification_Demo_NewBookingMessage));

    public static string Notification_Demo_SecurityAlertTitle => Get(nameof(Notification_Demo_SecurityAlertTitle));

    public static string Notification_Demo_SecurityAlertMessage => Get(nameof(Notification_Demo_SecurityAlertMessage));

    public static string Common_JustNow => Get(nameof(Common_JustNow));

    public static string Common_MinutesAgoFormat => Get(nameof(Common_MinutesAgoFormat));

    public static string Common_HoursAgoFormat => Get(nameof(Common_HoursAgoFormat));

    public static string Common_DaysAgoFormat => Get(nameof(Common_DaysAgoFormat));

    // Phase 28: Enterprise Global Search & Command Palette.
    public static string Search_Palette_Placeholder => Get(nameof(Search_Palette_Placeholder));

    public static string Search_Palette_NoResults => Get(nameof(Search_Palette_NoResults));

    public static string Search_Palette_RecentSearches => Get(nameof(Search_Palette_RecentSearches));

    public static string Search_Palette_ClearHistory => Get(nameof(Search_Palette_ClearHistory));

    public static string Search_Palette_Favorites => Get(nameof(Search_Palette_Favorites));

    public static string Search_Type_Page => Get(nameof(Search_Type_Page));

    public static string Search_Type_Customer => Get(nameof(Search_Type_Customer));

    public static string Search_Type_Booking => Get(nameof(Search_Type_Booking));

    public static string Search_Type_Specialist => Get(nameof(Search_Type_Specialist));

    public static string Search_Type_Service => Get(nameof(Search_Type_Service));

    public static string Search_Type_Product => Get(nameof(Search_Type_Product));

    public static string Search_Type_Command => Get(nameof(Search_Type_Command));

    public static string Search_Command_ToggleSidebar => Get(nameof(Search_Command_ToggleSidebar));

    public static string Search_Command_ToggleNotifications => Get(nameof(Search_Command_ToggleNotifications));

    public static string Search_Command_OpenHelp => Get(nameof(Search_Command_OpenHelp));

    public static string Search_Command_ToggleSilentMode => Get(nameof(Search_Command_ToggleSilentMode));

    public static string Search_Command_GoBack => Get(nameof(Search_Command_GoBack));

    public static string Search_Command_GoForward => Get(nameof(Search_Command_GoForward));

    public static string Search_Command_OpenBranchSwitcher => Get(nameof(Search_Command_OpenBranchSwitcher));

    /// <summary>Phase 29: Enterprise Workspace &amp; Window Management.</summary>
    public static string Search_Command_OpenWorkspaceSwitcher => Get(nameof(Search_Command_OpenWorkspaceSwitcher));

    public static string Workspace_HeaderButton_Tooltip => Get(nameof(Workspace_HeaderButton_Tooltip));

    public static string Workspace_Switcher_Title => Get(nameof(Workspace_Switcher_Title));

    public static string Workspace_Switcher_NewNamePlaceholder => Get(nameof(Workspace_Switcher_NewNamePlaceholder));

    public static string Workspace_Switcher_New => Get(nameof(Workspace_Switcher_New));

    public static string Workspace_Switcher_Recent => Get(nameof(Workspace_Switcher_Recent));

    public static string Workspace_Switcher_All => Get(nameof(Workspace_Switcher_All));

    public static string Workspace_Switcher_Rename => Get(nameof(Workspace_Switcher_Rename));

    public static string Workspace_Switcher_Duplicate => Get(nameof(Workspace_Switcher_Duplicate));

    public static string Workspace_Switcher_Delete => Get(nameof(Workspace_Switcher_Delete));

    public static string Workspace_Switcher_Reset => Get(nameof(Workspace_Switcher_Reset));

    public static string Workspace_Pane_SplitRight => Get(nameof(Workspace_Pane_SplitRight));

    public static string Workspace_Pane_SplitDown => Get(nameof(Workspace_Pane_SplitDown));

    public static string Workspace_Pane_FloatOut => Get(nameof(Workspace_Pane_FloatOut));

    public static string Workspace_Pane_ClosePane => Get(nameof(Workspace_Pane_ClosePane));

    public static string Workspace_Pane_CloseTab => Get(nameof(Workspace_Pane_CloseTab));

    public static string Workspace_Pane_AddTab => Get(nameof(Workspace_Pane_AddTab));

    public static string Workspace_DockPanel_Toggle => Get(nameof(Workspace_DockPanel_Toggle));

    public static string Workspace_Panel_Outline => Get(nameof(Workspace_Panel_Outline));

    public static string Workspace_Outline_Empty => Get(nameof(Workspace_Outline_Empty));

    public static string Workspace_Outline_CloseTooltip => Get(nameof(Workspace_Outline_CloseTooltip));

    /// <summary>
    /// Looks up a localized display label for a Domain enum member by its
    /// raw name (e.g. "Active", "Cancelled", "Cash") under the
    /// <c>Enum_&lt;MemberName&gt;</c> key convention - shared across every
    /// status/type/method enum in the app (CustomerStatus, BookingStatus,
    /// InvoiceStatus, PaymentMethod, etc.) since the same word ("Active",
    /// "Cancelled") means the same thing in every language regardless of
    /// which entity it describes, avoiding one key per enum type. Falls
    /// back to the raw member name itself (not the lookup key) so an
    /// enum value nobody has localized yet still renders something
    /// readable instead of a raw resx key string.
    /// </summary>
    public static string GetEnumLabel(string enumMemberName)
    {
        var key = $"Enum_{enumMemberName}";
        var value = Get(key);
        return value == key ? enumMemberName : value;
    }

    /// <summary>
    /// Phase 26: Smart Context Help. Generic dynamic key lookup - unlike
    /// every other property on this class (one named property per key,
    /// checked at compile time), a help topic's eleven content fields are
    /// addressed by <c>{KeyPrefix}_{FieldSuffix}</c> string concatenation
    /// (<see cref="Rojan.Desktop.Domain.Help.HelpTopic.KeyPrefix"/>'s own
    /// doc comment explains why), so there is no fixed set of property
    /// names to declare - the registry can grow to cover more
    /// modules/pages without a matching Strings.cs change every time.
    /// Falls back to the key itself (matching <see cref="Get"/>'s own
    /// missing-key behavior) rather than throwing, consistent with
    /// <see cref="GetEnumLabel"/>.
    /// </summary>
    public static string GetByKey(string key) => Get(key);
}
