// <auto-generated>
// Hand-maintained stand-in for a Visual-Studio-generated resx Designer.cs
// (no VS resx designer tool is available in this environment) - marked
// auto-generated so analyzers treat its resx-mirrored identifiers
// (Category_Key, matching every <data name="..."> in Strings*.resx) the
// same way they treat real generated code, consistent with how a real
// ResXFileCodeGenerator output would be excluded from CA1707 etc.
// </auto-generated>
#nullable enable
using System.Globalization;
using System.Reflection;
using System.Resources;

namespace Rojan.Desktop.Presentation.Localization;

/// <summary>
/// Strongly-typed wrapper over the <c>Strings.resx</c>/<c>Strings.en.resx</c>/
/// <c>Strings.ar.resx</c> satellite resource set - hand-written rather than
/// Visual-Studio-generated (no VS resx designer tool is available in this
/// environment), but reads through the exact same
/// <see cref="System.Resources.ResourceManager"/> mechanism a generated
/// Designer.cs would use, so the standard .NET satellite-assembly
/// resolution (driven by <see cref="CultureInfo.CurrentUICulture"/>, set
/// once at startup - see <c>Shell.Localization.LocalizationService</c>)
/// applies unchanged. XAML binds these directly via
/// <c>{x:Static loc:Strings.PropertyName}</c> - safe because the selected
/// language never changes mid-session (Phase 19A's "restart required"
/// design), so there is no need for these to be reactive/bindable
/// properties.
/// </summary>
public static class Strings
{
    private static readonly ResourceManager ResourceManager =
        new("Rojan.Desktop.Presentation.Localization.Strings", typeof(Strings).GetTypeInfo().Assembly);

    private static IReadOnlyDictionary<string, string>? _packOverrides;

    /// <summary>
    /// Lets a non-built-in Language Pack supply its own string values
    /// without recompiling this assembly - the concrete proof of "Future
    /// packs load their own resources": <c>Shell.Localization.LocalizationService</c>
    /// calls this with a pack's <c>"strings"</c> table (if any) at
    /// startup. Keys the pack does not define fall through to the
    /// compiled resx (<see cref="Get"/>'s second lookup) - honest partial-
    /// translation behavior, not a hard requirement that a pack cover
    /// every key.
    /// </summary>
    public static void SetPackOverrides(IReadOnlyDictionary<string, string>? overrides) => _packOverrides = overrides;

    private static string Get(string key)
    {
        if (_packOverrides is not null && _packOverrides.TryGetValue(key, out var overrideValue))
        {
            return overrideValue;
        }

        return ResourceManager.GetString(key, CultureInfo.CurrentUICulture) ?? key;
    }

    public static string Common_Search => Get(nameof(Common_Search));

    public static string Common_Back => Get(nameof(Common_Back));

    public static string Common_Forward => Get(nameof(Common_Forward));

    public static string Common_Notifications => Get(nameof(Common_Notifications));

    public static string Common_GuestUser => Get(nameof(Common_GuestUser));

    public static string Common_Minimize => Get(nameof(Common_Minimize));

    public static string Common_Maximize => Get(nameof(Common_Maximize));

    public static string Common_Close => Get(nameof(Common_Close));

    public static string Common_CollapseExpandNavigation => Get(nameof(Common_CollapseExpandNavigation));

    public static string Common_NoNotifications => Get(nameof(Common_NoNotifications));

    public static string Common_Loading => Get(nameof(Common_Loading));

    public static string Common_NoDataAvailable => Get(nameof(Common_NoDataAvailable));

    public static string Common_Retry => Get(nameof(Common_Retry));

    public static string Common_Ready => Get(nameof(Common_Ready));

    public static string Common_Home => Get(nameof(Common_Home));

    public static string Common_ViewingFormat => Get(nameof(Common_ViewingFormat));

    public static string Common_ErrorDialogMessage => Get(nameof(Common_ErrorDialogMessage));

    public static string Common_Save => Get(nameof(Common_Save));

    public static string Common_Cancel => Get(nameof(Common_Cancel));

    public static string Dashboard_Title => Get(nameof(Dashboard_Title));

    public static string Dashboard_Subtitle => Get(nameof(Dashboard_Subtitle));

    public static string Dashboard_KeyMetrics => Get(nameof(Dashboard_KeyMetrics));

    public static string Dashboard_QuickActions => Get(nameof(Dashboard_QuickActions));

    public static string Dashboard_RecentActivity => Get(nameof(Dashboard_RecentActivity));

    public static string Dashboard_AiAssistant => Get(nameof(Dashboard_AiAssistant));

    public static string Dashboard_ComingSoon => Get(nameof(Dashboard_ComingSoon));

    public static string Dashboard_AskAi => Get(nameof(Dashboard_AskAi));

    public static string Dashboard_QuickAction_NewBooking => Get(nameof(Dashboard_QuickAction_NewBooking));

    public static string Dashboard_QuickAction_AddClient => Get(nameof(Dashboard_QuickAction_AddClient));

    public static string Dashboard_QuickAction_CreateTask => Get(nameof(Dashboard_QuickAction_CreateTask));

    public static string Dashboard_QuickAction_ViewReports => Get(nameof(Dashboard_QuickAction_ViewReports));

    public static string Nav_Dashboard => Get(nameof(Nav_Dashboard));

    public static string Nav_Customers => Get(nameof(Nav_Customers));

    public static string Nav_Bookings => Get(nameof(Nav_Bookings));

    public static string Nav_Calendar => Get(nameof(Nav_Calendar));

    public static string Nav_Services => Get(nameof(Nav_Services));

    public static string Nav_Inventory => Get(nameof(Nav_Inventory));

    public static string Nav_Accounting => Get(nameof(Nav_Accounting));

    public static string Nav_StaffHr => Get(nameof(Nav_StaffHr));

    public static string Nav_Specialists => Get(nameof(Nav_Specialists));

    public static string Nav_Reports => Get(nameof(Nav_Reports));

    public static string Nav_Analytics => Get(nameof(Nav_Analytics));

    public static string Nav_AiCenter => Get(nameof(Nav_AiCenter));

    public static string Nav_Settings => Get(nameof(Nav_Settings));

    public static string Settings_Title => Get(nameof(Settings_Title));

    public static string Settings_Subtitle => Get(nameof(Settings_Subtitle));

    public static string Settings_Language_SectionTitle => Get(nameof(Settings_Language_SectionTitle));

    public static string Settings_Language_BuiltIn => Get(nameof(Settings_Language_BuiltIn));

    public static string Settings_Language_InstalledPacks => Get(nameof(Settings_Language_InstalledPacks));

    public static string Settings_Language_AvailableLanguages => Get(nameof(Settings_Language_AvailableLanguages));

    public static string Settings_Language_Download => Get(nameof(Settings_Language_Download));

    public static string Settings_Language_Install => Get(nameof(Settings_Language_Install));

    public static string Settings_Language_Remove => Get(nameof(Settings_Language_Remove));

    public static string Settings_Language_Update => Get(nameof(Settings_Language_Update));

    public static string Settings_Language_ComingSoon => Get(nameof(Settings_Language_ComingSoon));

    public static string Settings_Language_Apply => Get(nameof(Settings_Language_Apply));

    public static string Settings_Language_RestartRequired => Get(nameof(Settings_Language_RestartRequired));

    public static string Settings_Language_RestartNow => Get(nameof(Settings_Language_RestartNow));

    public static string Settings_Language_CurrentFormat => Get(nameof(Settings_Language_CurrentFormat));

    public static string Settings_Language_NoPacksInstalled => Get(nameof(Settings_Language_NoPacksInstalled));

    public static string Settings_Theme_SectionTitle => Get(nameof(Settings_Theme_SectionTitle));

    public static string Settings_Theme_Light => Get(nameof(Settings_Theme_Light));

    public static string Settings_Theme_Dark => Get(nameof(Settings_Theme_Dark));

    public static string Settings_Theme_System => Get(nameof(Settings_Theme_System));

    public static string Settings_Theme_CurrentFormat => Get(nameof(Settings_Theme_CurrentFormat));

    public static string Settings_Theme_Apply => Get(nameof(Settings_Theme_Apply));

    public static string Settings_Theme_RestartRequired => Get(nameof(Settings_Theme_RestartRequired));

    public static string Settings_Theme_RestartNow => Get(nameof(Settings_Theme_RestartNow));

    public static string Nav_Organizations => Get(nameof(Nav_Organizations));

    public static string Shell_BranchSwitcher => Get(nameof(Shell_BranchSwitcher));

    public static string Organizations_Title => Get(nameof(Organizations_Title));

    public static string Organizations_Subtitle => Get(nameof(Organizations_Subtitle));

    public static string Organizations_Refresh => Get(nameof(Organizations_Refresh));

    public static string Organizations_Section_Organizations => Get(nameof(Organizations_Section_Organizations));

    public static string Organizations_Section_Branches => Get(nameof(Organizations_Section_Branches));

    public static string Organizations_Section_BranchSettings => Get(nameof(Organizations_Section_BranchSettings));

    public static string Organizations_Section_Permissions => Get(nameof(Organizations_Section_Permissions));

    public static string Organizations_Section_Session => Get(nameof(Organizations_Section_Session));

    public static string Organizations_CreateOrganization => Get(nameof(Organizations_CreateOrganization));

    public static string Organizations_Name => Get(nameof(Organizations_Name));

    public static string Organizations_LegalName => Get(nameof(Organizations_LegalName));

    public static string Organizations_TaxInformation => Get(nameof(Organizations_TaxInformation));

    public static string Organizations_Subscription => Get(nameof(Organizations_Subscription));

    public static string Organizations_AllOrganizations => Get(nameof(Organizations_AllOrganizations));

    public static string Organizations_CreateBranch => Get(nameof(Organizations_CreateBranch));

    public static string Organizations_BranchName => Get(nameof(Organizations_BranchName));

    public static string Organizations_BranchCode => Get(nameof(Organizations_BranchCode));

    public static string Organizations_BranchAddress => Get(nameof(Organizations_BranchAddress));

    public static string Organizations_BranchPhone => Get(nameof(Organizations_BranchPhone));

    public static string Organizations_BranchEmail => Get(nameof(Organizations_BranchEmail));

    public static string Organizations_BranchManager => Get(nameof(Organizations_BranchManager));

    public static string Organizations_BranchTimeZone => Get(nameof(Organizations_BranchTimeZone));

    public static string Organizations_BranchCurrency => Get(nameof(Organizations_BranchCurrency));

    public static string Organizations_AllBranches => Get(nameof(Organizations_AllBranches));

    public static string Organizations_OpenTime => Get(nameof(Organizations_OpenTime));

    public static string Organizations_CloseTime => Get(nameof(Organizations_CloseTime));

    public static string Organizations_WorkingDays => Get(nameof(Organizations_WorkingDays));

    public static string Organizations_Monday => Get(nameof(Organizations_Monday));

    public static string Organizations_Tuesday => Get(nameof(Organizations_Tuesday));

    public static string Organizations_Wednesday => Get(nameof(Organizations_Wednesday));

    public static string Organizations_Thursday => Get(nameof(Organizations_Thursday));

    public static string Organizations_Friday => Get(nameof(Organizations_Friday));

    public static string Organizations_Saturday => Get(nameof(Organizations_Saturday));

    public static string Organizations_Sunday => Get(nameof(Organizations_Sunday));

    public static string Organizations_VatPercentage => Get(nameof(Organizations_VatPercentage));

    public static string Organizations_ReceiptHeader => Get(nameof(Organizations_ReceiptHeader));

    public static string Organizations_ReceiptFooter => Get(nameof(Organizations_ReceiptFooter));

    public static string Organizations_ShowLogo => Get(nameof(Organizations_ShowLogo));

    public static string Organizations_MinNoticeHours => Get(nameof(Organizations_MinNoticeHours));

    public static string Organizations_MaxAdvanceBookingDays => Get(nameof(Organizations_MaxAdvanceBookingDays));

    public static string Organizations_AllowSameDayBooking => Get(nameof(Organizations_AllowSameDayBooking));

    public static string Organizations_EmailEnabled => Get(nameof(Organizations_EmailEnabled));

    public static string Organizations_SmsEnabled => Get(nameof(Organizations_SmsEnabled));

    public static string Organizations_ReminderHours => Get(nameof(Organizations_ReminderHours));

    public static string Organizations_SaveSettings => Get(nameof(Organizations_SaveSettings));

    public static string Organizations_SettingsSaved => Get(nameof(Organizations_SettingsSaved));

    public static string Organizations_CurrentOrganization => Get(nameof(Organizations_CurrentOrganization));

    public static string Organizations_CurrentBranch => Get(nameof(Organizations_CurrentBranch));

    public static string Organizations_CurrentRole => Get(nameof(Organizations_CurrentRole));

    public static string Organizations_SwitchRole => Get(nameof(Organizations_SwitchRole));

    public static string Organizations_Code => Get(nameof(Organizations_Code));

    public static string Organizations_OrgPhone => Get(nameof(Organizations_OrgPhone));

    public static string Organizations_OrgEmail => Get(nameof(Organizations_OrgEmail));

    public static string Organizations_OrgAddress => Get(nameof(Organizations_OrgAddress));

    public static string Shell_BranchSwitcher_SearchPlaceholder => Get(nameof(Shell_BranchSwitcher_SearchPlaceholder));

    public static string Shell_BranchSwitcher_Favorites => Get(nameof(Shell_BranchSwitcher_Favorites));

    public static string Shell_BranchSwitcher_Recent => Get(nameof(Shell_BranchSwitcher_Recent));
}
